---
language: node_js
node_js:
  - '4.0'
  - '4.1'
  - '5.0'
env:
  global:
    - COVERAGE=false
matrix:
  include:
    - node_js: "4.0"
      env: COVERAGE=true
after_success:
  - "[ $COVERAGE == false ] || npm run istanbul -- --report text-summary"
