version = 0.1
default-task = 'build'

extensions = ['chomp@0.1:npm', 'chomp@0.1:prettier']

[[task]]
name = 'build'
deps = ['dist/cli.js', 'docs.md']

[[task]]
target = 'dist/cli.js'
deps = ['src/**/*.ts', 'npm:install']
run = 'esbuild src/cli.ts --bundle --platform=node --external:@jspm/generator --external:ora --external:picocolors --external:@babel/core --format=esm --outfile=$TARGET'

[[task]]
name = 'docs'
target = 'docs.md'
deps = ['src/**/*.ts', 'docs/intro.md', 'docs/config.md', 'dist/cli.js']
run = '''
  node docs/generate.js > docs.md
  node docs/finalize.js
'''

[[task]]
name = 'lint'
run = 'eslint .'

[[task]]
name = 'lint:fix'
run = 'eslint . --fix'

[[task]]
name = 'prettier'
template = 'prettier'
deps = ['src/**/*.ts', 'test/*.ts']
[task.template-options]
files = 'src/**/*.ts test/*.ts'
loglevel = 'warn'

[[task]]
name = 'typecheck'
deps = ['src/**/*.ts', 'test/*.ts']
run = 'tsc --noEmit'

[[task]]
name = 'link:test'
dep = 'build'
run = 'node jspm.js link ./test/fixtures/test.js --env=deno,node'

[[task]]
name = 'deno:test'
dep = 'link:test'
run = 'deno --unstable run --importmap importmap.json -A ./test/fixtures/test.js'

[[task]]
name = 'test'
dep = 'test:'

[[task]]
name = 'test:##'
dep = 'test/##.test.ts'
run = 'tsx $DEP'
